educate_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pledge_donations.urls', namespace='pledge_donations')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pledge_donations/urls.py
from django.urls import path
from . import views

app_name = 'pledge_donations'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),
    path('info/', views.ProblemStatementView.as_view(), name='problem-statement'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('contact/success/', views.ContactSuccessView.as_view(), name='contact_success'),
    path('faq/', views.FaqView.as_view(), name='faq'),
    path('event/', views.EventListView.as_view(), name='event_list'),
    path('event/<slug:slug>/', views.EventDetail.as_view(), name='event_details'),
    path('books/', views.EventListView.as_view(), name='books_list'),
    path('subscribe/', views.SubscribeView.as_view(), name='subscribe'),
    path('subscription/success/', views.SubscriptionSuccessView.as_view(), name='subscription_success'),
    # path('test', views.TesterView.as_view(), name='tester_page'),
]

pledge_donations/models.py
from django.db import models
from django.conf import settings


class Contact(models.Model):
    contact_name = models.CharField(max_length=150)
    contact_email = models.EmailField(blank=False)
    message_title = models.CharField(max_length=200)
    message = models.TextField()
    has_reached_out = models.BooleanField(default=False, blank=True)


class Books(models.Model):
    name = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='books/')
    total_donated = models.IntegerField(default=0)
    grade_level = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='events/', default='default.png')
    slug = models.SlugField(max_length=200)
    description = models.CharField(max_length=400)
    venue_state = models.CharField(max_length=20)
    venue_lga = models.CharField(max_length=100)
    venue_street_address = models.CharField(max_length=300)
    volunteers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='events', blank=True)
    books = models.ManyToManyField(Books, related_name='events', blank=True)
    event_time = models.DateTimeField(auto_now_add=True)
    donation_amount = models.DecimalField(decimal_places=2, max_digits=20, blank=True)
    donation_goal = models.DecimalField(decimal_places=2, max_digits=20, blank=True)
    volunteer_goal = models.IntegerField(default=0, blank=True)
    book_goal = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.name


class Donations(models.Model):
    donor = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    amount = models.DecimalField(decimal_places=2, blank=True, max_digits=20)
    event = models.ForeignKey(Event,
                              related_name='donations',
                              on_delete=models.DO_NOTHING)
    donation_time = models.DateTimeField(auto_now_add=True, blank=False)
    donation_type = models.CharField(blank=False, max_length=5)
    books = models.ForeignKey(Books, related_name='donations', on_delete=models.DO_NOTHING, null=True)
    fulfilled = models.BooleanField(default=False)
    item_count = models.IntegerField(default=1)

    def __str__(self):
        return self.donor.username + '-' + str(self.id)


class Subscription(models.Model):
    email = models.EmailField(blank=False, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True, blank=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    is_organisation = models.BooleanField(default=False)

    def __str__(self):
        return self.username

pledge_donations/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from .models import Contact, Subscription


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = '__all__'

    def send_email(self):
        # TODO: optimise to use celery
        send_mail(subject='Educate-Me Newsletter Subscription Registration',
                  message='Welcome to educate-Me\'s Newsletter. \n Your email address will never be shared with any '
                          'other organisations. You can unsubscribe anytime from your account dashboard.'
                          'We hope you don\'t though :)',
                  from_email=settings.DEFAULT_FROM_EMAIL,
                  recipient_list=[self.cleaned_data['email']])

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

pledge_donations/views.py
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from django.http import JsonResponse

from .forms import ContactForm, SubscribeForm
from .models import Event, Donations

from .utils import get_book_donations_event


class LandingPageView(TemplateView):
    template_name = 'pledge_donations/index.html'


class ProblemStatementView(TemplateView):
    template_name = 'pledge_donations/problem-statement.html'


class ContactView(CreateView):
    form_class = ContactForm
    template_name = 'pledge_donations/contact.html'
    success_url = '/contact/success/'


class ContactSuccessView(TemplateView):
    template_name = 'account/contact_success.html'


class FaqView(TemplateView):
    template_name = 'pledge_donations/faq.html'


class EventListView(ListView):
    model = Event
    paginate_by = 9
    template_name = 'pledge_donations/event_list.html'
    context_object_name = 'events'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        events = Event.objects.all()

        event_breakdown = []
        for event in events:
            event_breakdown.append({
                'name': event.name,
                'slug': event.slug,
                'amount_raised': event.donation_amount,
                'amount_goal': event.donation_goal,
                'donated_books_count': get_book_donations_event(event.id),
                'donated_books_goal': event.book_goal,
                'volunteers_count': event.volunteers.count(),
                'volunteer_goal': event.volunteer_goal,
                'donation_percentage': (event.donation_amount / event.donation_goal) * 100,
                'progress_position': ((event.donation_amount / event.donation_goal) * 100) - 5,
            })

        context['events'] = event_breakdown
        return context


class EventDetail(DetailView):
    model = Event
    template_name = 'pledge_donations/event_detail.html'
    context_object_name = 'event'


class BooksList(ListView):
    model = ''
    template_name = ''


class SubscribeView(CreateView):
    form_class = SubscribeForm
    success_url = '/subscription/success/'

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

    def form_invalid(self, form):
        return JsonResponse({'message': 'Error occurred while processing input',
                             'errors': form.errors.as_json()}, status=400)


class SubscriptionSuccessView(TemplateView):
    template_name = 'account/subscription_successful.html'


class TesterView(TemplateView):
    template_name = 'account/password_reset_done.html'

users/views.py
from django.shortcuts import render

# Create your views here.

templates/pledge_donations/contact.html
{% extends 'pledge_donations/pledge_base.html' %}
{% load  static %}

{% block css-files %}
    <link rel="stylesheet" href="{% static 'resources/css/problem-info.css' %}">
    <link rel="stylesheet" href="{% static 'resources/css/contact.css' %}">
{% endblock %}


{% block page-title %}
    Educate Me - Contact
{% endblock %}

{% block page-heading %}
    Contact Us
{% endblock %}

{% block page-sub-heading %}
    Home / <span class="yellow-text">Contact</span>
{% endblock %}

{% block page-body %}
    <section id="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h6 class="section-title-small">Reach out to us</h6>
                    <form action="{% url 'pledge_donations:contact' %}" method="post" class="contact-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <small id="emailHelp" class="form-text text-muted error-text">
                                {{ form.non_field_errors }}
                            </small>
                            <label for="id_name">Full Name</label>
                            <input type="text" class="form-control shadow-none" id="id_name" placeholder="Your Name"
                                   name="contact_name">
                            <small id="emailHelp" class="form-text text-muted">
                                {{ form.contact_name.errors.as_text }}
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email Address</label>
                            <input type="email" class="form-control shadow-none" id="id_email"
                                   placeholder="Email" name="contact_email">
                            <small id="emailHelp" class="form-text text-muted">
                                {{ form.contact_email.errors.as_text }}
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="id_message_title">Message Title</label>
                            <input type="text" class="form-control shadow-none" id="id_message_title"
                                   name="message_title" placeholder="Title of your message">
                            <small id="emailHelp" class="form-text text-muted">
                                {{ form.message_title.errors.as_text }}
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="id_message">Message</label>
                            <textarea name="message" rows="5" class="form-control shadow-none"
                                      id="id_message" placeholder="Message you want to send"></textarea>
                            <small id="emailHelp" class="form-text text-muted">
                                {{ form.message.errors.as_text }}
                            </small>
                        </div>
                        <button type="submit" class="btn btn-block submit-btn mt-4">Send Message</button>
                    </form>
                </div>
                <div class="col-sm-6 pt-5 pl-5">
                    <h6 class="section-title-big section-title">
                        Contact Us Directly
                    </h6>
                    <div class="row">
                        <div class="address-box col-md-5">
                            <p class="main-location mb-3">
                                Abuja Office
                            </p>
                            <div class="icon-name-container">
                                Address
                            </div>
                            <p class="address-text">
                                203 Fake St. Grand Avenue, Maitama, Abuja, Nigeria
                            </p>
                            <div class="icon-name-container">
                                Phone
                            </div>
                            <p class="address-text">
                                +234 815 6227 194 <br>
                                +234 903 4686 700
                            </p>
                            <div class="icon-name-container">
                                Email
                            </div>
                            <p class="address-text">
                                contact@educate.me <br>
                                hello@educate.me
                            </p>
                        </div>
                        <div class="address-box col-md-5">
                            <p class="main-location mb-3">
                                Lagos Office
                            </p>
                            <div class="icon-name-container">
                                Address
                            </div>
                            <p class="address-text">
                                102 Fake St. Grand Avenue, Ikeja, Lagos, Nigeria
                            </p>
                            <div class="icon-name-container">
                                Phone
                            </div>
                            <p class="address-text">
                                +234 815 6227 194 <br>
                                +234 903 4686 700
                            </p>
                            <div class="icon-name-container">
                                Email
                            </div>
                            <p class="address-text">
                                contact@educate.me <br>
                                hello@educate.me
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for event in events %}
                    <div class="col-sm-4">
                        <div class="cause-card">
                            <img src="{% static 'resources/images/girl-writing.png' %}" alt="girl-writing"
                                 class="cause-image">
                            <div class="cause-details-box">
                                <p class="cause-title">
                                    {{ event.name }}
                                </p>
                                <div class="progress-metric-container">
                                    <div class="progress-value" style="left: {{ event.progress_position }}%">
                                        <span>{{ event.donation_percentage }}</span>%
                                    </div>
                                    <div class="progress" style="height: 5px">
                                        <div class="progress-bar" role="progressbar"
                                             style="width: {{ event.donation_percentage }}%; font-size: 90%;
                                                     background-color: #f7c33f;" aria-valuenow="50" aria-valuemin="0"
                                             aria-valuemax="100">
                                        </div>
                                    </div>
                                    <div>
                                        <p class="left-metric-text-container ">
                                            <span class="focus">Raised:</span>
                                            <span class="normal">{{ event.amount_raised }}</span>
                                        </p>
                                        <p class="right-metric-text-container ">
                                            <span class="focus">Goal:</span>
                                            <span class="normal">{{ event.amount_goal }}</span>
                                        </p>
                                    </div>
                                </div>

                                <div class="number-metrics">
                                    <p class="cause-metric-text">
                                        <span class="yellow-highlight">{{ event.donated_books_count }}</span>
                                        <span class="blue-highlight">/{{ event.donated_books_goal }}</span> <br>
                                        <span class="cause-metric-name">Books</span>
                                    </p>
                                    <p class="cause-metric-text">
                                        <span class="yellow-highlight">{{ event.volunteers_count }}</span>
                                        <span class="blue-highlight">/{{ event.volunteer_goal }}</span> <br>
                                        <span class="cause-metric-name">Volunteers</span>
                                    </p>
                                </div>
                            </div>
                            <div class="button-groups">
                                <a href="{% url 'pledge_donations:event_details' event.slug %}"
                                   class="cause-details-button">Learn More</a>
                                <a href="#" class="cause-action-button">
                                    <img src="{% static 'resources/images/money.png' %}" alt="books">
                                </a>
                                <a href="#" class="cause-action-button">
                                    <img src="{% static 'resources/images/book.png' %}" alt="books">
                                </a>
                                <a href="#" class="cause-action-button">
                                    <img src="{% static 'resources/images/community.png' %}" alt="books">
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/pledge_donations/events_list.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'resources/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'resources/css/problem-info.css' %}">
    <link rel="stylesheet" href="{% static 'resources/css/causes.css' %}">
    <link rel="stylesheet" href="{% static 'resources/css/queries.css' %}">
    <title>Educate Me - Contact</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
        <a class="navbar-brand" href="{% url 'pledge_donations:landing' %}">
            <img src="{% static 'resources/images/educate-logo-white-cropped.png' %}" alt="educate-me-logo"
                 class="site-logo">
        </a>
        <button class="custom-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link main-nav" href="/#about-section">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link main-nav" href="{% url 'pledge_donations:event_list' %}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link main-nav" href="/#testimonies-section">Testimonies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link main-nav" href="{% url 'pledge_donations:contact' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="main-nav hero-button hero-button-full login-button"
                       href="{% url 'account_login' %}">Login</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col d-flex justify-content-center pt-5 flex-column align-content-center">
                <h1 class="hero-main-text">
                    Upcoming/Ongoing <span class="yellow-text">Events</span>
                </h1>
                <p class="hero-sub-text">
                    How can I donate?
                </p>
            </div>
        </div>
    </div>
</header>

<section id="causes-section">
    <div class="container">
        <div class="row">
            <div class="col">
                <h6 class="section-title-small center-section">Events</h6>
                <h6 class="section-title-big center-section">
                    Ongoing events you can contribute to
                </h6>
            </div>
        </div>
        <div class="row">
            {% for event in events %}
                <div class="col-sm-4">
                    <div class="cause-card">
                        <img src="{% static 'resources/images/girl-writing.png' %}" alt="girl-writing"
                             class="cause-image">
                        <div class="cause-details-box">
                            <p class="cause-title">
                                {{ event.name }}
                            </p>
                            <div class="progress-metric-container">
                                <div class="progress-value" style="left: {{ event.progress_position }}%">
                                    <span>{{ event.donation_percentage }}</span>%
                                </div>
                                <div class="progress" style="height: 5px">
                                    <div class="progress-bar" role="progressbar"
                                         style="width: {{ event.donation_percentage }}%; font-size: 90%;
                                                 background-color: #f7c33f;" aria-valuenow="50" aria-valuemin="0"
                                         aria-valuemax="100">
                                    </div>
                                </div>
                                <div>
                                    <p class="left-metric-text-container ">
                                        <span class="focus">Raised:</span>
                                        <span class="normal">{{ event.amount_raised }}</span>
                                    </p>
                                    <p class="right-metric-text-container ">
                                        <span class="focus">Goal:</span>
                                        <span class="normal">{{ event.amount_goal }}</span>
                                    </p>
                                </div>
                            </div>

                            <div class="number-metrics">
                                <p class="cause-metric-text">
                                    <span class="yellow-highlight">{{ event.donated_books_count }}</span>
                                    <span class="blue-highlight">/{{ event.donated_books_goal }}</span> <br>
                                    <span class="cause-metric-name">Books</span>
                                </p>
                                <p class="cause-metric-text">
                                    <span class="yellow-highlight">{{ event.volunteers_count }}</span>
                                    <span class="blue-highlight">/{{ event.volunteer_goal }}</span> <br>
                                    <span class="cause-metric-name">Volunteers</span>
                                </p>
                            </div>
                        </div>
                        <div class="button-groups">
                            <a href="{% url 'pledge_donations:event_details' event.slug %}"
                               class="cause-details-button">Learn More</a>
                            <a href="#" class="cause-action-button">
                                <img src="{% static 'resources/images/money.png' %}" alt="books">
                            </a>
                            <a href="#" class="cause-action-button">
                                <img src="{% static 'resources/images/book.png' %}" alt="books">
                            </a>
                            <a href="#" class="cause-action-button">
                                <img src="{% static 'resources/images/community.png' %}" alt="books">
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>


<footer id="footer-section">
    <div class="container">
        <div class="row">
            <div class="col">
                <h6 class="section-title-big center-section footer-header">
                    Subscribe to our Newsletter
                </h6>
                <form action="{% url 'pledge_donations:subscribe' %}" method="post" class="subscribe-form">
                    {% csrf_token %}
                    <div class="input-group subscribe-container">
                        <input type="email" name="email" id="email-field-newsletter"
                               class="form-control shadow-none subscribe-input" placeholder="Email Address" required>
                        <button class="input-group-text subscribe-button">
                            Subscribe
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <div class="footer-section-box">
                    <img src="{% static 'resources/images/educate-logo-white-cropped.png' %}" alt="site-logo"
                         class="footer-logo">
                    <p class="footer-logo-text">
                        Education is the most powerful weapon which you can use to change the world.
                        Change a child's world today.
                    </p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="footer-section-box no-top">
                    <p class="footer-section-title d-none d-md-block" style="color: #062265">Navigation</p>
                    <ul class="footer-links">
                        <li><a href="{% url 'pledge_donations:landing' %}">Home</a></li>
                        <li><a href="{% url 'pledge_donations:landing' %}#about-section">About</a></li>
                        <li><a href="{% url 'pledge_donations:faq' %}">FAQ's</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="footer-section-box no-top">
                    <p class="footer-section-title d-none d-md-block" style="color: #062265">.</p>
                    <ul class="footer-links">
                        <li style="text-align: left"><a href="{% url 'pledge_donations:event_list' %}">Events</a>
                        <li style="text-align: left"><a href="{% url 'pledge_donations:contact' %}">Contact</a>
                        <li style="text-align: left"><a href="{% url 'pledge_donations:books_list' %}">Needed Book
                            List</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="footer-section-box no-top">
                    <p class="footer-section-title">Contact Info</p>
                    <ul class="footer-links">
                        <li class="contact-item">
                            <ion-icon name="location-outline" class="contact-icon"></ion-icon>
                            203 Fake St. Grand Avenue, Maitama, Abuja, Nigeria
                        </li>
                        <li class="contact-item">
                            <ion-icon name="call-outline" class="contact-icon"></ion-icon>
                            +2 392 3929 210
                        </li>
                        <li class="contact-item">
                            <ion-icon name="mail-outline" class="contact-icon"></ion-icon>
                            contact@educate.me
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous">
</script>
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
</body>
</html>